[versions]
agp = "8.13.2"
androidsvgAar = "1.4"
androidxJunit = "1.3.0"
apiVersion = "82"
bsh = "2.0b5"
constraintlayoutVersion = "2.2.1"
espressoCoreVersion = "3.7.0"
hutoolAll = "5.8.43"
gson = "2.13.2"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
constraintlayout = "2.1.4"
materialVersion = "1.11.0"
navigationFragment = "2.6.0"
navigationFragmentVersion = "2.7.7"
navigationUi = "2.6.0"
appcompatVersion = "1.7.1"
navigationUiVersion = "2.7.7"
firebaseCrashlyticsBuildtools = "3.0.6"

[libraries]
androidsvg-aar = { module = "com.caverock:androidsvg-aar", version.ref = "androidsvgAar" }
androidx-constraintlayout-v221 = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
androidx-espresso-core-v370 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
androidx-junit-v130 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-navigation-fragment-v277 = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationFragmentVersion" }
androidx-navigation-ui-v277 = { module = "androidx.navigation:navigation-ui", version.ref = "navigationUiVersion" }
bsh = { module = "org.beanshell:bsh", version.ref = "bsh" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hutool-all = { module = "cn.hutool:hutool-all", version.ref = "hutoolAll" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v1110 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompatVersion" }
xposed-api = { module = "de.robv.android.xposed:api", version.ref = "apiVersion" }
firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

